---
title: "Restaurant Inspection Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

```{r}

data("rest_inspec")

inspec_data =
rest_inspec %>% 
drop_na(score) %>%
separate(inspection_date, into = c("year", "month-day"), sep = 4) %>% 
  select(
    boro, critical_flag, cuisine_description, year, score, zipcode) %>%
  mutate(
    cuisine_description = case_when(
      cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" ~ "Latin",
      cuisine_description == "Sandwiches/Salads/Mixed Buffet" ~ "Mixed Buffet",
      TRUE ~ as.character(cuisine_description))
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Mean Score of Cuisine Types in Washington Heights

```{r}

inspec_data %>%
  filter(boro == "MANHATTAN" & zipcode == 10032) %>% 
  group_by(cuisine_description) %>%
  summarize(
    score_mean = mean(score)
  ) %>% 
  plot_ly(
    x = ~fct_reorder(cuisine_description, score_mean), y = ~score_mean, type = "bar",
    color = ~cuisine_description, colors = "Set2", alpha = .7
  ) %>% 
    layout(
    xaxis = list(
      title = "Cuisine Category",
      autotick = FALSE, tick0 = 1, dtick = 1),
    yaxis = list(
      title = "Mean Score"
    ))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Critical Flags in Boroughs Over Time

```{r}

inspec_data %>% 
  filter(critical_flag == "Critical" & boro != "Missing") %>% 
  group_by(boro, year) %>% 
  summarize(n = n()) %>% 
  plot_ly(
    y = ~n, x = ~year, type = "scatter", mode = "lines",
    color = ~boro, colors = "Set2"
  ) %>% 
  layout(
    xaxis = list(
      title = "Year",
      autotick = FALSE, tick0 = 1, dtick = 1),
    yaxis = list(
      title = "Number of Critical Flags"
    ))
```

### American Food Score distribution in Different Boroughs

```{r}

inspec_data %>%
  filter(year == 2017 & cuisine_description == "American" & boro != "Missing") %>% 
  group_by (boro, cuisine_description) %>% 
  plot_ly(
    color= ~boro, y= ~score, type = "box", colors = "Set2", alpha = .7
  ) %>%
  layout(
    xaxis = list(
      showticklabels = FALSE,
      title = "Borough",
      autotick = FALSE, tick0 = 1, dtick = 1),
    yaxis = list(
      title = "Score"
    ))
```
